MyFirstSiteCore/MyFirstSiteCore/Models/ErrorViewModel.cs
using System;

namespace MyFirstSiteCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyFirstSiteCore/MyFirstSiteCore/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFirstSiteCore.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult About_As()
        {
            return View();
        }
    }
}

MyFirstSiteCore/MyFirstSiteCore/Controllers/ContController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFirstSiteCore.Controllers
{
    public class ContController : Controller
    {
        public IActionResult Contact()
        {
            return View();
        }
    }
}

MyFirstSiteCore/MyFirstSiteCore/Controllers/GellController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFirstSiteCore.Controllers
{
    public class GellController : Controller
    {
        public IActionResult Gallery()
        {
            return View();
        }
    }
}

MyFirstSiteCore/MyFirstSiteCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstSiteCore.Models;

namespace MyFirstSiteCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyFirstSiteCore/MyFirstSiteCore/Controllers/ServController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyFirstSiteCore.Controllers
{
    public class ServController : Controller
    {
        public IActionResult Services()
        {
            return View();
        }
    }
}

MyFirstSiteCore/MyFirstSiteCore/Views/AboutUs/About_As.cshtml
@{
    ViewData["Title"] = "About_As";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section banner-page" data-background="images/about.jpg">
    <div class="content-wrap pos-relative">
        <div class="d-flex justify-content-center bd-highlight mb-2">
            <div class="title-page">About Us</div>
        </div>
        <p class="text-center text-white">Your pet's health and well-being are our top priority.</p>
    </div>
</div>
<div id="veterinary" class="section-border">
    <div class="content-wrap">
        <div class="container">

            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <h2 class="section-heading text-center text-primary no-after mb-5">
                        Meet Veterinary
                    </h2>
                    <p class="subheading text-center">Your pet's health and well-being are our top priority.</p>
                </div>
            </div>

            <div class="row mt-4">

                <!-- Item 1 -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="rs-team-1">
                        <div class="media">
                            <img src="/images/image1.jpg" alt="" class="img-fluid">
                            <div class="sosmed-icon">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                            </div>
                        </div>
                        <div class="body">
                            <div class="title">Dr. John Doel</div>
                            <div class="text-primary">Veterinary</div>
                        </div>
                    </div>
                </div>

                <!-- Item 2 -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="rs-team-1">
                        <div class="media">
                            <img src="/images/image2.jpg" alt="" class="img-fluid">
                            <div class="sosmed-icon">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                            </div>
                        </div>
                        <div class="body">
                            <div class="title">Dr. Mellisa Doel</div>
                            <div class="text-primary">Veterinary</div>
                        </div>
                    </div>
                </div>

                <!-- Item 3 -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="rs-team-1">
                        <div class="media">
                            <img src="/images/image3.jpg" alt="" class="img-fluid">
                            <div class="sosmed-icon">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                            </div>
                        </div>
                        <div class="body">
                            <div class="title">Dr. Aldizza Doel</div>
                            <div class="text-primary">Veterinary</div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-12 col-md-12 text-center">
                    <a href="#" class="btn btn-sec mt-5">Check More</a>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="section">
    <div class="content-wrap content-wrap-40">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <h2 class="section-heading text-center text-primary no-after mb-5">
                        Our Awards
                    </h2>
                    <p class="subheading text-center">Your pet's health and well-being are our top priority.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-sm-4 col-md-2">
                    <div class="client-img">
                        <a href="#">
                            <img src="/images/client1.png" alt="" class="img-fluid">
                        </a>
                    </div>
                </div>

                <div class="col-6 col-sm-4 col-md-2">
                    <div class="client-img">
                        <a href="#"><img src="/images/client2.png" alt="" class="img-fluid"></a>
                    </div>
                </div>

                <div class="col-6 col-sm-4 col-md-2">
                    <div class="client-img">
                        <a href="#"><img src="/images/client3.png" alt="" class="img-fluid"></a>
                    </div>
                </div>

                <div class="col-6 col-sm-4 col-md-2">
                    <div class="client-img">
                        <a href="#"><img src="/images/client4.png" alt="" class="img-fluid"></a>
                    </div>
                </div>

                <div class="col-6 col-sm-4 col-md-2">
                    <div class="client-img">
                        <a href="#"><img src="/images/client5.png" alt="" class="img-fluid"></a>
                    </div>
                </div>

                <div class="col-6 col-sm-4 col-md-2">
                    <div class="client-img">
                        <a href="#"><img src="/images/client6.png" alt="" class="img-fluid"></a>
                    </div>
                </div>
					
            </div>
        </div>
    </div>
</div>

MyFirstSiteCore/MyFirstSiteCore/Views/Cont/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section banner-page3" data-background="images/dummy-img-1920x300.jpg">
    <div class="content-wrap pos-relative">
        <div class="d-flex justify-content-center bd-highlight mb-2">
            <div class="title-page">Contact</div>
        </div>
        <p class="text-center text-white">Your pet's health and well-being are our top priority.</p>
    </div>
</div>
<div id="class" class="">
    <div class="content-wrap">
        <div class="container">

            <div class="row mt-4">

                <!-- Item 1 -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="rs-icon-info-4 mb-5">
                        <div class="icon">
                            <i class="fa fa-smile-o"></i>
                        </div>
                        <div class="body">
                            <h3 class="title">Address</h3>
                            <p class="mb-1">Krivoy Rog 5-Gornyatskiy</p>
                        </div>
                    </div>
                </div>

                <!-- Item 2 -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="rs-icon-info-4 mb-5">
                        <div class="icon">
                            <i class="fa fa-envelope"></i>
                        </div>
                        <div class="body">
                            <h3 class="title">Email</h3>
                            <p class="mb-1">opletinenko@gmail.com</p>
                        </div>
                    </div>
                </div>

                <!-- Item 3 -->
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="rs-icon-info-4 mb-5">
                        <div class="icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="body">
                            <h3 class="title">Address</h3>
                            <p class="mb-1">+38(098)620 36 96</p>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-12 col-md-12 mb-5">
                    <h2 class="section-heading text-center text-primary no-after mb-5">
                        Send Us A Message
                    </h2>
                    <p class="subheading text-center">Your pet's health and well-being are our top priority.</p>
                </div>



                <div class="col-12 col-sm-12 col-md-12">
                    <form  class="form-contact" id="contactForm" method="post" data-toggle="validator" novalidate="true">
                        <div class="row">
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="p_name" placeholder="Enter Name" required="">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input type="email" class="form-control" id="p_email" placeholder="Enter Email" required="">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="p_subject" placeholder="Subject">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="p_phone" placeholder="Enter Phone Number">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <textarea id="p_message" class="form-control" rows="6" placeholder="Enter Your Message"></textarea>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <div class="text-center">
                                <div class="text-danger opovechenie">По заданию не отпровляем не чего!!!</div>
                                <div id="success"></div>
                                <button type="submit" class="btn btn-primary btn_sabmit">SEND MESSAGE</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>

MyFirstSiteCore/MyFirstSiteCore/Views/Gell/Gallery.cshtml
@{
    ViewData["Title"] = "Gallery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section banner-page" data-background="images/about.jpg">
    <div class="content-wrap pos-relative">
        <div class="d-flex justify-content-center bd-highlight mb-2">
            <div class="title-page">Gallery</div>
        </div>
        <p class="text-center text-white">Your pet's health and well-being are our top priority.</p>
    </div>
</div>
<div id="class" class="">
    <div class="content-wrap">
        <div class="container">

            <div class="row">

                <div class="col-12 col-sm-12 col-md-12">
                    <div class="row popup-gallery gutter-5">
                        <!-- ITEM 1 -->
                        <div class="col-sm-6 col-md-4">
                            <div class="box-gallery">
                                <a href="/images/gallery1.jpg" title="Gallery #1">
                                    <img src="/images/gallery1.jpg" alt="" class="img-fluid">
                                    <div class="project-info">
                                        <div class="project-icon">
                                            <span class="fa fa-search"></span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- ITEM 2 -->
                        <div class="col-sm-6 col-md-4">
                            <div class="box-gallery">
                                <a href="/images/gallery2.jpg" title="Gallery #2">
                                    <img src="/images/gallery2.jpg" alt="" class="img-fluid">
                                    <div class="project-info">
                                        <div class="project-icon">
                                            <span class="fa fa-search"></span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- ITEM 3 -->
                        <div class="col-sm-6 col-md-4">
                            <div class="box-gallery">
                                <a href="/images/gallery3.jpg" title="Gallery #3">
                                    <img src="/images/gallery3.jpg" alt="" class="img-fluid">
                                    <div class="project-info">
                                        <div class="project-icon">
                                            <span class="fa fa-search"></span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- ITEM 4 -->
                        <div class="col-sm-6 col-md-4">
                            <div class="box-gallery">
                                <a href="/images/gallery4.jpg" title="Gallery #4">
                                    <img src="/images/gallery4.jpg" alt="" class="img-fluid">
                                    <div class="project-info">
                                        <div class="project-icon">
                                            <span class="fa fa-search"></span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- ITEM 5 -->
                        <div class="col-sm-6 col-md-4">
                            <div class="box-gallery">
                                <a href="/images/gallery5.jpg" title="Gallery #5">
                                    <img src="/images/gallery5.jpg" alt="" class="img-fluid">
                                    <div class="project-info">
                                        <div class="project-icon">
                                            <span class="fa fa-search"></span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- ITEM 6 -->
                        <div class="col-sm-6 col-md-4">
                            <div class="box-gallery">
                                <a href="/images/gallery6.jpg" title="Gallery #6">
                                    <img src="/images/gallery6.jpg" alt="" class="img-fluid">
                                    <div class="project-info">
                                        <div class="project-icon">
                                            <span class="fa fa-search"></span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

MyFirstSiteCore/MyFirstSiteCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstSiteCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link href="~/lib/bootstrap/dist/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/lib/owlCarousel/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/lib/owlCarousel/css/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/animate.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <a href="#0" class="cd-top cd-is-visible cd-fade-out">Top</a>
    <div class="header-1">
        <div class="topbar d-none d-md-block">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-sm-6 col-md-6">
                        <p class="mb-0">
                            Welcome to my site</p>
                    </div>

                    <div class="col-sm-6 col-md-6">
                        <div class="sosmed-icon d-inline-flex pull-right">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>


                </div>
            </div>
        </div>
        <div class="middlebar d-none d-sm-block">
            <div class="container">
                <div class="contact-info mt-1">
                    <div class="box-icon-1">
                        <div class="icon">
                            <div class="fa fa-phone"></div>
                        </div>
                        <div class="body-content">
                            <div class="heading">Call Today :</div>
                            +38(098)620 36 96
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="navbar-main">
            <div class="container">
                <nav id="navbar-example" class="navbar navbar-expand-lg">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="/images/client5.png" alt="" />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Home" asp-action="Index">
                                    HOME
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="AboutUs" asp-action="About_As">ABOUT US</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Serv" asp-action="Services">
                                    SERVICES
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Gell" asp-action="Gallery">
                                    GALLERY
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Cont" asp-action="Contact">CONTACT</a>
                            </li>

                        </ul>
                        <a href="#" class="btn btn-secondary btn-nav btn-rect ml-auto">GET AN APPOINTMENT</a>
                    </div>
                </nav> 

            </div>
        </div>
    </div>
    <partial name="_CookieConsentPartial" />
    @RenderBody()

    <div class="foot bg-overlay-secondary" data-background="images/dummy-img-1920x900-3.jpg">
        <div class="content-wrap">
            <div class="container">

                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <div class="footer-item">
                            <img src="/images/logo_footer.png" alt="logo bottom" class="logo-bottom">
                            <div class="spacer-20"></div>
                            <p>We are pets center at vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.</p>
                            <div class="spacer-20"></div>
                            <img src="/images/payment.png" alt="">
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-4">
                        <div class="footer-item">
                            <div class="footer-title">
                                Opening Hours
                            </div>
                            <p>Our support available to help you 24 hours a day. We provide our best.</p>
                            <ul class="list">
                                <li>
                                    Mon - Fri : 08.00 am - 20.00 pm
                                </li>
                                <li>
                                    Saturday : 09.00 am - 20.00 pm
                                </li>
                                <li>
                                    Sunday :  We Are Closed
                                </li>
                            </ul>

                        </div>
                    </div>

                    <div class="col-sm-6 col-md-4">
                        <div class="footer-item">
                            <div class="footer-title">
                                Contact Info
                            </div>
                            <p>Lit sed The Best in dolor sit amet consectetur</p>
                            <ul class="list-info">
                                <li>
                                    <div class="info-icon text-primary">
                                        <span class="fa fa-map-marker"></span>
                                    </div>
                                    <div class="info-text">Krivoy rog 5-gornyatskiy</div>
                                </li>
                                <li>
                                    <div class="info-icon text-primary">
                                        <span class="fa fa-phone"></span>
                                    </div>
                                    <div class="info-text">+38(098)620 36 96</div>
                                </li>
                                <li>
                                    <div class="info-icon text-primary">
                                        <span class="fa fa-envelope"></span>
                                    </div>
                                    <div class="info-text">opletinenko@gmail.com</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="fcopy">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-6">
                        <p class="ftex">&copy; 2019 Your Company. Oleg <span class="text-primary">Pletinenko</span></p>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="sosmed-icon d-inline-flex float-right">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
<script src="~/lib/bootstrap/dist/js/jquery.magnific-popup.min.js" asp-append-version="true"></script>
<script src="~/lib/owlCarousel/js/owl.carousel.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>